name: Rust Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ {name: x86_64-pc-windows-gnu}, {name: x86_64-unknown-linux-musl} ]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: nightly
          RUSTTARGET: ${{ matrix.target.name }}
          STATIC_LINKING: true
          EXTRA_FILES: "README.md LICENSE config.toml"
